import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from './contexts/darkThemeContext';

export const metadata: Metadata = {
  title: "Mizuki TANIGUCHI's Portfolio",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" className='dark'>
        <body className="flex justify-center">{children}</body>
      </html>
    </ThemeProvider>
  );
}
